seed: 202505

llm:
  llm_name: OpenAI
  # llm_model: /data1/zhushengmao/Qwen2___5-14B-Instruct
  llm_model: qwen-plus
  # llm_url: http://localhost:8001/v1
  llm_url: https://dashscope.aliyuncs.com/compatible-mode/v1
  embed_name: OpenAI
  embed_model: /data1/zhushengmao/gte_Qwen2-7B-instruct
  embed_url: http://localhost:8002/v1
  api_key: sk-2b26e585f3aa4c17b949f2e675a5284e

# data
topic: example
data_path_raw: dataset_raw/example.json
data_path: dataset/example.json
num_users: 20
sampling_strategy: "active_by_time" # "random" "active" "active_by_time"

# simulation
react_strategy: "batch"
simulate_with_data: False
interval: 30M
time_intv: 24H
time_init_begin: "2024-02-01 00:00:00"
time_init_end: "2024-02-11 00:00:00"
time_sim_begin: "2024-02-11 00:00:00"
time_sim_end: "2024-02-12 00:00:00"
load_model: /data1/zhushengmao/save/example/model_init/model.json
save_path: /data1/zhushengmao/save/example

time_window_size: 12H  # 前后各[time_window_size]
active_window_size: 3H
neg_sample_num: 1
max_thread_num: 1
max_workers: 50
parallel: True
debug: False