llm:
  llm_name: OpenAI
  llm_model: /data1/zhushengmao/Qwen2___5-14B-Instruct
  llm_url: http://localhost:8001/v1
  embed_name: OpenAI
  embed_model: /data1/zhushengmao/gte_Qwen2-7B-instruct
  embed_url: http://localhost:8002/v1
seed: 202503
parallel: True
debug: False
react_strategy: "all"
simulate_with_data: False
topic: example
data_path: dataset/example.json
num_users: 20
interval: 8H
time_init_begin: "2023-08-01 00:00:00"
time_init_end: "2023-08-11 00:00:00"
time_sim_begin: "2023-08-11 00:00:00"
time_sim_end: "2023-08-13 00:00:00"
load_model: ""
save_path: /data1/zhushengmao/save/example